language: go

go:
  - 1.9
  - "1.10"
  - "1.11"
  - "1.12"
  - tip

script: make test-static

matrix:
  allow_failures:
    - go: tip

git:
  submodules: false

before_install:
  - git submodule update --init

branches:
  only:
  - master
  - /v\d+/
  - next
